# import = ["~/.config/alacritty/themes/themes/coolnight.toml"]
# import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]
import = ["~/.config/alacritty/themes/themes/aura.toml"]
[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 4

decorations = "Buttonless"

# opacity = 0.40
opacity = 0.85
# opacity = 0.00
# opacity = 0.93
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 12
